# Generated by Django 4.1 on 2022-08-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_resume_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/images/profile.png', null=True, upload_to=''),
        ),
    ]
